name:                dayofweek
version:             0.1.0.0
github:              "stetrevor/dayofweek"
license:             BSD3
author:              "Trevor Wong"
maintainer:          "stephen.trevor.wong@outlook.com"
copyright:           "Trevor Wong"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stetrevor/dayofweek#readme>

dependencies:
- base >= 4.7 && < 5
- selective
- polysemy
- polysemy-plugin

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -flate-specialise
- -fspecialise-aggressively
- -fplugin=Polysemy.Plugin

default-extensions:
- NamedFieldPuns
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies
- BlockArguments

library:
  source-dirs: src

executables:
  dayofweek-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dayofweek

tests:
  dayofweek-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dayofweek
    - HUnit
    - QuickCheck
    - hspec